metadata_dir: ./metadata
metadata_id_col: AriaId
data_dir: ../../Corpus_Test/xml
musescore_dir: ../../Corpus_Test/musescore
expand_repeats: false
window_size: null
overlap: 2
parallel: true
max_processes: 7
log:
  file_path: logs/musif_test.log
  file_level: DEBUG
  console_level: DEBUG

basic_modules:
  - scoring
  - file_name
  - metadata
  - themeA

features:
  - core
  - composer
  - librettist
  - ambitus
  - interval
  - tempo
  - density
  - texture
  - harmony
  - lyrics
  - scale
  - scale_relative
  - key
  - dynamics    
  - rhythm

split_keywords:  # Used to split the possible layers present depending on the instrument name
  - woodwind
  - brass
  - wind
  - viola
  - strings.cello
  - bass
  - oboi
  
parts_filter:
  # - vnI
  # - vnII
  # - obI
  # - obII
  # - va
  # - bs
  # - sop
  # - ten
  # - alt
  # - bar
  # - bass
  # - bbar
